/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ImagesToPdfRouteImport } from './routes/images-to-pdf'
import { Route as PdfToImagesRouteImport } from './routes/pdf-to-images'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesToPdfRoute = ImagesToPdfRouteImport.update({
  id: '/images-to-pdf',
  path: '/images-to-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfToImagesRoute = PdfToImagesRouteImport.update({
  id: '/pdf-to-images',
  path: '/pdf-to-images',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/images-to-pdf': typeof ImagesToPdfRoute
  '/pdf-to-images': typeof PdfToImagesRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/images-to-pdf': typeof ImagesToPdfRoute
  '/pdf-to-images': typeof PdfToImagesRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/images-to-pdf': typeof ImagesToPdfRoute
  '/pdf-to-images': typeof PdfToImagesRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/about' | '/images-to-pdf' | '/pdf-to-images' | '/privacy' | '/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/about' | '/images-to-pdf' | '/pdf-to-images' | '/privacy' | '/terms'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/images-to-pdf'
    | '/pdf-to-images'
    | '/privacy'
    | '/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ImagesToPdfRoute: typeof ImagesToPdfRoute
  PdfToImagesRoute: typeof PdfToImagesRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images-to-pdf': {
      id: '/images-to-pdf'
      path: '/images-to-pdf'
      fullPath: '/images-to-pdf'
      preLoaderRoute: typeof ImagesToPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-to-images': {
      id: '/pdf-to-images'
      path: '/pdf-to-images'
      fullPath: '/pdf-to-images'
      preLoaderRoute: typeof PdfToImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ImagesToPdfRoute: ImagesToPdfRoute,
  PdfToImagesRoute: PdfToImagesRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
